### ISSUE TITLE
Please add a screen shot to the readme

### ISSUE THREAD

**Issue by unixorn** [mvinan/malev-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by mvinan** [comment]
Hello. @unixorn great, you are absolutely right! I just uploaded the screenshots a few days ago.
I hope it can be of help.
